name: 'validate-detections'
description: 'Validate Microsoft Sentinel Analytics Rules. Supported file types for detection rules are ARM templates (json) and yml files'
inputs:
  filesPath:
    description:  'The path containing the detection rules.'
    required: false
    default: '.'

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/action.ps1 -FilesPath ${{ inputs.filesPath }}
      shell: pwsh
